#!/bin/bash -eu

echo "Installing Homebrew..."
curl -fsSL -o /tmp/brew-install https://raw.githubusercontent.com/Homebrew/install/master/install
/usr/bin/ruby /tmp/brew-install
brew doctor
brew update

brew tap homebrew/bundle
brew bundle
