#!/bin/bash -eu

echo "Installing Homebrew..."
curl -fsSL -o /tmp/brew-install https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
/bin/bash /tmp/brew-install
brew doctor
brew update

brew tap homebrew/bundle
brew bundle
