#!/bin/bash -eu

touch /usr/local/etc/dnsmasq.conf
echo -e "\nconf-file=${HOME}/.dotfiles/config/dnsmasq.conf" >> /usr/local/etc/dnsmasq.conf

sudo mkdir -p /etc/resolver/
sudo touch /etc/resolver/test
echo -e "nameserver 127.0.0.1\n" | sudo tee -a /etc/resolver/test

sudo brew services start dnsmasq
