#!/bin/bash -eu

# cp /usr/local/opt/dnsmasq/dnsmasq.conf.example /usr/local/etc/dnsmasq.conf
touch /usr/local/etc/dnsmasq.conf
echo -e "\nconf-file=${HOME}/.dotfiles/dnsmasq.conf" >> /usr/local/etc/dnsmasq.conf

sudo touch /etc/resolver/app
echo -e "nameserver 127.0.0.1\n" | sudo tee -a /etc/resolver/app

