#!/bin/bash -eu

echo "Setting Fish as Defualt Shell..."
echo $(which fish) | sudo tee -a /etc/shells
chsh -s $(which fish)

touch ~/.config/fish/config.fish
echo "source ~/.dotfiles/fish/config.fish" >> ~/.config/fish/config.fish
