#!/bin/bash -eu

git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
git config --global user.name "Grant Butler"
git config --global user.email "grantjbutler@users.noreply.github.com"

