#!/bin/bash -eu

git config --global pull.ff only

git config --global init.defaultBranch main
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
git config --global user.name "Grant Butler"
git config --global user.email "grantjbutler@users.noreply.github.com"

git config --global alias.undo "reset --soft HEAD~1"
git config --global alias.publish "push -u origin HEAD"

git config --global merge.tool vscode
git config --global mergetool.vscode.cmd "code --wait \$MERGED"
git config --global diff.tool vscode
git config --global difftool.vscode.cmd "code --wait --diff \$LOCAL \$REMOTE"

gh auth login

