#!/bin/bash

# Finder
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"
defaults write com.apple.finder ShowStatusBar -bool true

defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false

defaults write com.apple.finder NewWindowTarget -string "PfHm"
defaults write com.apple.finder NewWindowTargetPath -string "file:///Users/"$(whoami)"/"

defaults write NSGlobalDomain AppleShowAllExtensions -bool true
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

defaults write com.apple.finder EmptyTrashSecurely -bool true

# Dock
defaults write com.apple.dock autohide -bool true

# Safari
defaults write com.apple.Safari AutoFillPasswords -bool false
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

defaults write com.apple.Safari "ShowFavoritesBar-v2" -bool false
defaults write com.apple.Safari ShowOverlayStatusBar -bool true

defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled" -bool true

defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

# Photos
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

# Xcode
defaults write com.apple.dt.Xcode DVTTextShowLineNumbers -bool true
defaults write com.apple.dt.Xcode DVTTextShowPageGuide -bool true
defaults write com.apple.dt.Xcode DVTTextPageGuideLocation -int 80

defaults write com.apple.dt.Xcode DVTTextUsesSyntaxAwareIndenting -bool false

defaults write com.apple.dt.Xcode IDESourceControlAutomaticallyAddNewFiles -bool false

# Security
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 5

# SystemUIServer
mkdir ~/Pictures/Screenshots/
defaults write com.apple.screencapture location ~/Pictures/Screenshots/

# iTerm2

# Read configuration from custom directory
defaults write com.googlecode.iterm2 PrefsCustomFolder -string "~/.dotfiles/config/iterm"
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true

# Tweetbot
# https://twitter.com/dancounsell/status/667011332894535682
defaults write com.tapbots.TweetbotMac OpenURLsDirectly YES

programs=("cfprefsd" "Dock" "Finder" "Photos" "Safari" "SystemUIServer" "Xcode")
for app in ${programs[@]}; do
    killall "${app}" > /dev/null 2>&1
done

echo "Done. Note that some of these changes require a logout/restart to take effect."
