#!/bin/bash -eu

vagrant box add laravel/homestead --provider virtualbox

pushd ~

git clone https://github.com/laravel/homestead.git .homestead
cd .homestead
git checkout release

bash init.sh

popd

composer global require "laravel/installer"
