#!/bin/bash -eu

code --install-extension Orta.vscode-ios-common-files
code --install-extension octref.vetur
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension ryannaddy.laravel-artisan
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension calebporzio.better-phpunit

json -I -f "$HOME/Library/Application Support/Code/User/settings.json" -e 'this["editor.minimap.enabled"]=false'
json -I -f "$HOME/Library/Application Support/Code/User/settings.json" -e 'this["editor.wordWrap"]="on"'
json -I -f "$HOME/Library/Application Support/Code/User/settings.json" -e 'this["terminal.extenal.osxExec"]="iTerm.app"'
json -I -f "$HOME/Library/Application Support/Code/User/settings.json" -e 'this["window.zoomLevel"]=0'
json -I -f "$HOME/Library/Application Support/Code/User/settings.json" -e 'this["php.suggest.basic"]=false'
json -I -f "$HOME/Library/Application Support/Code/User/settings.json" -e 'this["eslint.autoFixOnSave"]=true'
json -I -f "$HOME/Library/Application Support/Code/User/settings.json" -e 'this["eslint.validate"]=["javascript","javascriptreact","vue"]'

